#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
    path: /
    controller: App\Controller\HomeController::index
inscri:
    path: /inscri
    controller: App\Controller\InscriController::index
inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index
affichage:
    path: /affichage
    controller: App\Controller\AffichageController::index
Gest:
    path: /Gest
    controller: App\Controller\GestProduitController::index

reg:
    path: /reg
    controller: App\Controller\RegistrationController::new